server:
  port : 8081
spring:
  profiles:
    active: local
  application:
    name: "hello-word"
management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#    distribution:
#      percentiles-histogram:
#        http: true
