version: "3.4"

services:
  spring-boot-prometheus-grafana:
    build: ./spring-boot-prometheus-grafana
    ports:
      - "8081:8081"
    container_name: spring-boot-prometheus-grafana
    networks:
      - prometheus-grafana-network
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus
    networks:
      - prometheus-grafana-network
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    container_name: grafana
    networks:
      - prometheus-grafana-network
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
    external: true
networks:
  prometheus-grafana-network: